version: "3.6"
services:
  postgres:
    image: postgres:14
    ports:
      - "5832:5432" # expose pg on port 5832 to not collide with pg from elsewhere
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      # Avoid using init SQL scripts here because Postgres restarts after running them,
      # which causes timing issues when starting the database and then immediately trying to connect to it.
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db_data:
