version: "3.6"
services:
  postgres:
    image: postgres:14
    ports:
      - "5832:5432" # expose pg on port 5832 to not collide with pg from elsewhere
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./prisma/initdb.sql:/docker-entrypoint-initdb.d/1-initdb.sql
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db_data:
