name: E2E-testing
on: [push]
jobs:
  e2e:
    env:
      DATABASE_URL: postgresql://postgres:@localhost:5432/appdb
      NODE_ENV: test
      NEXTAUTH_SECRET: supersecret
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["16.x"]
        os: [ubuntu-latest]
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: appdb
        ports:
          - 5432:5432
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # - name: Install deps and build (with cache)
      #   uses: bahmutov/npm-install@v1
      - run: npm install

      - name: Next.js cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/package-lock.json') }}-nextjs

      - run: npx playwright install --with-deps
      - run: npm run lint
      - run: npm run build
      - run: npm run test-start
      - run: npm run test-dev
      - run: npm test

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test results
          path: |
            playwright/test-results
